language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get install -qq xorg-dev

script:
  - cargo build --verbose
  - cargo build --release --verbose

matrix:
  include:
    env: FMT
    rust: stable
    install:
      - rustup component add rustfmt-preview
    script:
      - cargo fmt -- --check
